name: Build APK from ZIP
on:
  workflow_dispatch:
  push: { branches: [ main, master ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip project.zip
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          unzip -o project.zip -d .
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Build debug APK
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TraumaGalery-APK
          path: app/build/outputs/apk/debug/app-debug.apk
